- name: Deploy ceph VM
  hosts: all
  gather_facts: False
  remote_user: ceph

  vars:
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
    - vm_name: "{{ inventory_hostname }}"
    - vm_image: "/var/lib/libvirt/images/{{ vm_name }}.img"
  tasks:


    - name: Generate uuid
      shell: uuidgen
      register: uuid
      delegate_to: localhost

    - name: Generate MAC
      shell: echo "52:54:$(dd if=/dev/urandom count=1 2>/dev/null | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4/')"
      register: mac
      delegate_to: localhost

    - name: Generate virsh templates
      template: src=templates/cephVM.xml dest=/tmp/{{ inventory_hostname }}.xml
      delegate_to: localhost

    - name: Get images into /var/lib/libvirt/images
      shell: if [ ! -e /var/lib/libvirt/images/*.img ]; then cd /var/lib/libvirt/images && wget ftp://labossi.hpintelco.org/pub/labceph/{{ vm_name }}.img.gz ; fi
      delegate_to: localhost
      sudo: True

    - name: Gunzip images
      shell: if [ ! -e /var/lib/libvirt/images/*.img ]; then cd /var/lib/libvirt/images && gunzip {{ vm_name }}.img.gz ; fi
      delegate_to: localhost
      sudo: True

    - name: Create vm
      shell: virsh create /tmp/{{ vm_name }}.xml
      delegate_to: localhost

    - name: Define vm
      shell: virsh define /tmp/{{ vm_name }}.xml
      delegate_to: localhost

    - name: Wait vm readiness
      pause :  seconds=30

    - name: remove target host old servers identities from local known_hosts list
      shell: ssh-keygen -R  {{ item }}
      with_items:
        - "{{ inventory_hostname }}"
      delegate_to: localhost

    - name: get target host current fingerprint
      shell: ssh-keyscan {{ hash_option | default("")}} {{ inventory_hostname }} >> {{ known_hosts_file }}
      delegate_to: localhost

    - name: Stop ntp service
      service: name=ntp state=stopped
      sudo: True

    - name: Update time
      shell: ntpdate ntp.hpintelco.org
      sudo: True

    - name: Configure ntp
      template: src=templates/ntp.conf dest=/etc/ntp.conf
      sudo: True

    - name: Restart ntp service
      service: name=ntp state=restarted
      sudo: True
