- name: Deploy ceph VM
  hosts: all
  gather_facts: False
  remote_user: root
  sudo: yes
  vars:
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
  
  tasks:

    

    - name: starting vagrant environment 
      shell: chdir=~/labceph vagrant up --provider=libvirt
      delegate_to: localhost
      run_once: true
 
    - name: Remove target host old servers identities from local known_hosts list
      shell: ssh-keygen -R  {{ inventory_hostname }}
      delegate_to: localhost
      ignore_errors: yes
 
    - name: create .ssh dir
      sudo: no 
      shell: mkdir -p `dirname {{ known_hosts_file }}`; chmod 700 `dirname {{ known_hosts_file }}`
      delegate_to: localhost

    - name : Get target host current fingerprint
      sudo:  no
      shell : ssh-keyscan {{ hash_option | default("")}} {{ inventory_hostname }} >> {{ known_hosts_file }}
      delegate_to : localhost

#    - name: Stop ntp service
#      service: name=ntp state=stopped
#      sudo: True

#    - name: Update time
#      shell: ntpdate ntp.hpintelco.org
#      sudo: True

#   - name: Configure ntp
#      template: src=templates/ntp.conf dest=/etc/ntp.conf
#      sudo: True

#   - name: Restart ntp service
#      service: name=ntp state=restarted
#      sudo: True
