- name: Deploy ceph on VM
  hosts: adm
  gather_facts: False
  remote_user: ceph

  vars:
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
    - ceph_conf: "/home/ceph/ceph-cluster/ceph.conf"
  tasks:

    - name: Copy clean script
      copy: src=ceph/reset_ceph.sh dest={{ home_dir }} owner=ceph group=ceph mode=0774

    - name: Create cluter directory
      shell: if [ -e ~/ceph-cluster ]; then echo "Directory exist"; else mkdir ~/ceph-cluster ;fi

    - name: Create monitor
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf new cephosd1

    - name: Change replication parameter
      lineinfile: dest="{{ ceph_conf }}" line="osd pool default size = 2" insertafter="filestore_xattr_use_omap"

    - name: Install ceph
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf install cephadm cephosd1 cephosd2 cephosd3 cephgw

    - name: Initialize monitor
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf mon create-initial

    - name: Prepare OSD
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf osd prepare cephosd1:/osd/osd1 cephosd1:/osd/osd2 cephosd2:/osd/osd1 cephosd2:/osd/osd2

    - name: Activate OSD
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf osd activate cephosd1:/osd/osd1 cephosd1:/osd/osd2 cephosd2:/osd/osd1 cephosd2:/osd/osd2

    - name: Deploy keys
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf admin cephadm cephosd1 cephosd2 cephosd3 cephgw

    - name: Deploy rgw
      shell: cd  ~/ceph-cluster && ceph-deploy --overwrite-conf rgw create cephgw
